/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SplatRouteImport } from "./routes/$";
import { Route as AdvanceRouteImport } from "./routes/advance";
import { Route as Dc_vmuRouteImport } from "./routes/dc_vmu";
import { Route as DebugRouteImport } from "./routes/debug";
import { Route as FilesRouteImport } from "./routes/files";
import { Route as N64_ctrlpakRouteImport } from "./routes/n64_ctrlpak";
import { Route as OtaRouteImport } from "./routes/ota";
import { Route as PresetsRouteImport } from "./routes/presets";
import { Route as SystemRouteImport } from "./routes/system";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any);
const AdvanceRoute = AdvanceRouteImport.update({
  id: "/advance",
  path: "/advance",
  getParentRoute: () => rootRouteImport,
} as any);
const Dc_vmuRoute = Dc_vmuRouteImport.update({
  id: "/dc_vmu",
  path: "/dc_vmu",
  getParentRoute: () => rootRouteImport,
} as any);
const DebugRoute = DebugRouteImport.update({
  id: "/debug",
  path: "/debug",
  getParentRoute: () => rootRouteImport,
} as any);
const FilesRoute = FilesRouteImport.update({
  id: "/files",
  path: "/files",
  getParentRoute: () => rootRouteImport,
} as any);
const N64_ctrlpakRoute = N64_ctrlpakRouteImport.update({
  id: "/n64_ctrlpak",
  path: "/n64_ctrlpak",
  getParentRoute: () => rootRouteImport,
} as any);
const OtaRoute = OtaRouteImport.update({
  id: "/ota",
  path: "/ota",
  getParentRoute: () => rootRouteImport,
} as any);
const PresetsRoute = PresetsRouteImport.update({
  id: "/presets",
  path: "/presets",
  getParentRoute: () => rootRouteImport,
} as any);
const SystemRoute = SystemRouteImport.update({
  id: "/system",
  path: "/system",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/advance": typeof AdvanceRoute;
  "/dc_vmu": typeof Dc_vmuRoute;
  "/debug": typeof DebugRoute;
  "/files": typeof FilesRoute;
  "/n64_ctrlpak": typeof N64_ctrlpakRoute;
  "/ota": typeof OtaRoute;
  "/presets": typeof PresetsRoute;
  "/system": typeof SystemRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/advance": typeof AdvanceRoute;
  "/dc_vmu": typeof Dc_vmuRoute;
  "/debug": typeof DebugRoute;
  "/files": typeof FilesRoute;
  "/n64_ctrlpak": typeof N64_ctrlpakRoute;
  "/ota": typeof OtaRoute;
  "/presets": typeof PresetsRoute;
  "/system": typeof SystemRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/advance": typeof AdvanceRoute;
  "/dc_vmu": typeof Dc_vmuRoute;
  "/debug": typeof DebugRoute;
  "/files": typeof FilesRoute;
  "/n64_ctrlpak": typeof N64_ctrlpakRoute;
  "/ota": typeof OtaRoute;
  "/presets": typeof PresetsRoute;
  "/system": typeof SystemRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$"
    | "/advance"
    | "/dc_vmu"
    | "/debug"
    | "/files"
    | "/n64_ctrlpak"
    | "/ota"
    | "/presets"
    | "/system";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/$"
    | "/advance"
    | "/dc_vmu"
    | "/debug"
    | "/files"
    | "/n64_ctrlpak"
    | "/ota"
    | "/presets"
    | "/system";
  id:
    | "__root__"
    | "/"
    | "/$"
    | "/advance"
    | "/dc_vmu"
    | "/debug"
    | "/files"
    | "/n64_ctrlpak"
    | "/ota"
    | "/presets"
    | "/system";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SplatRoute: typeof SplatRoute;
  AdvanceRoute: typeof AdvanceRoute;
  Dc_vmuRoute: typeof Dc_vmuRoute;
  DebugRoute: typeof DebugRoute;
  FilesRoute: typeof FilesRoute;
  N64_ctrlpakRoute: typeof N64_ctrlpakRoute;
  OtaRoute: typeof OtaRoute;
  PresetsRoute: typeof PresetsRoute;
  SystemRoute: typeof SystemRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$": {
      id: "/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/advance": {
      id: "/advance";
      path: "/advance";
      fullPath: "/advance";
      preLoaderRoute: typeof AdvanceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dc_vmu": {
      id: "/dc_vmu";
      path: "/dc_vmu";
      fullPath: "/dc_vmu";
      preLoaderRoute: typeof Dc_vmuRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/debug": {
      id: "/debug";
      path: "/debug";
      fullPath: "/debug";
      preLoaderRoute: typeof DebugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/files": {
      id: "/files";
      path: "/files";
      fullPath: "/files";
      preLoaderRoute: typeof FilesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/n64_ctrlpak": {
      id: "/n64_ctrlpak";
      path: "/n64_ctrlpak";
      fullPath: "/n64_ctrlpak";
      preLoaderRoute: typeof N64_ctrlpakRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ota": {
      id: "/ota";
      path: "/ota";
      fullPath: "/ota";
      preLoaderRoute: typeof OtaRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/presets": {
      id: "/presets";
      path: "/presets";
      fullPath: "/presets";
      preLoaderRoute: typeof PresetsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/system": {
      id: "/system";
      path: "/system";
      fullPath: "/system";
      preLoaderRoute: typeof SystemRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdvanceRoute: AdvanceRoute,
  Dc_vmuRoute: Dc_vmuRoute,
  DebugRoute: DebugRoute,
  FilesRoute: FilesRoute,
  N64_ctrlpakRoute: N64_ctrlpakRoute,
  OtaRoute: OtaRoute,
  PresetsRoute: PresetsRoute,
  SystemRoute: SystemRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
